Models/Slide.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MVCKurumsalSiteProje.Models
{
    public class Slide : IEntity
    {
        public int Id { get; set; }
        [Display(Name = "Başlık"), StringLength(250)]
        public string Title { get; set; }
        [StringLength(100)]
        public string Url { get; set; }
        [Display(Name = "Açıklama"), StringLength(500), DataType(DataType.MultilineText)]
        public string Description { get; set; }
        [Display(Name = "Resim"), StringLength(100), Required, DataType(DataType.ImageUrl)]
        public string Image { get; set; }
        [Display(Name = "Eklenme Tarihi"), ScaffoldColumn(false)]
        public DateTime? CreateDate { get; set; } = DateTime.Now;
    }
}

Areas/Admin/Controllers/SlidesController.cs
using MVCKurumsalSiteProje.Data;
using MVCKurumsalSiteProje.Models;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MVCKurumsalSiteProje.Areas.Admin.Controllers
{
    [Authorize]
    public class SlidesController : Controller
    {
        DatabaseContext context = new DatabaseContext();
        // GET: Admin/Slides
        public ActionResult Index()
        {
            return View(context.Slides.ToList());
        }

        // GET: Admin/Slides/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Slides/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Slides/Create
        [HttpPost]
        public ActionResult Create(Slide collection, HttpPostedFileBase Image)
        {
            try
            {
                // TODO: Add insert logic here
                if (Image != null)
                {
                    collection.Image = Image.FileName;
                    Image.SaveAs(Server.MapPath("/Images/" + Image.FileName));
                }
                context.Slides.Add(collection);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError("", "Hata Oluştu!");
            }
            return View(collection);
        }

        // GET: Admin/Slides/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var data = context.Slides.Find(id);
            if (data == null)
            {
                return HttpNotFound();
            }
            return View(data);
        }

        // POST: Admin/Slides/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Slide collection, HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (Image != null)
                    {
                        collection.Image = Image.FileName;
                        Image.SaveAs(Server.MapPath("/Images/" + Image.FileName));
                    }
                    context.Entry(collection).State = System.Data.Entity.EntityState.Modified;
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    ModelState.AddModelError("", "Hata Oluştu!");
                }
            }
            return View(collection);
        }

        // GET: Admin/Slides/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var data = context.Slides.Find(id);
            if (data == null)
            {
                return HttpNotFound();
            }
            return View(data);
        }

        // POST: Admin/Slides/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Slide collection)
        {
            try
            {
                // TODO: Add delete logic here
                var data = context.Slides.Find(id);
                if (data != null)
                {
                    context.Slides.Remove(data);
                    context.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Areas/Admin/Views/Slides/Create.cshtml
@model MVCKurumsalSiteProje.Models.Slide

@{
    ViewBag.Title = "Slide Ekle";
}

<h2>Slide Ekle</h2>

@using (Html.BeginForm("Create", "Slides", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control", type = "file" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Dön", "Index")
</div>

Areas/Admin/Views/Slides/Delete.cshtml
@model MVCKurumsalSiteProje.Models.Slide

@{
    ViewBag.Title = "Sil";
}

<h2>Sil</h2>

<h3>Silmek istiyor musunuz?</h3>
<div>
    <h4>Slide</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="~/Images/@Model.Image" alt="Resim Yüklenmemiş" height="75" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-danger" /> |
            @Html.ActionLink("Listeye Dön", "Index")
        </div>
    }
</div>

Areas/Admin/Views/Slides/Edit.cshtml
@model MVCKurumsalSiteProje.Models.Slide

@{
    ViewBag.Title = "Slide Düzenle";
}

<h2>Slide Düzenle</h2>

@using (Html.BeginForm("Edit", "Slides", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CreateDate)
        @Html.HiddenFor(model => model.Image)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control", type = "file" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                <img src="~/Images/@Model.Image" alt="Resim Yüklenmemiş" height="75" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Dön", "Index")
</div>

Areas/Admin/Views/Slides/Index.cshtml
@model IEnumerable<MVCKurumsalSiteProje.Models.Slide>

@{
    ViewBag.Title = "Slider Resimleri";
}

<h2>Slider Resimleri</h2>

<p>
    @Html.ActionLink("Yeni Ekle", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Url)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <img src="~/Images/@item.Image" alt="Resim Yüklenmemiş" height="34" />
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Sil", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>